USE [DWMgmt]
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[CAT].[DF_REG_0300_CDate]') AND type = 'D')
BEGIN
ALTER TABLE [CAT].[REG_0300_Object_registry] DROP CONSTRAINT [DF_REG_0300_CDate]
END

GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[CAT].[REG_0300_Object_registry]') AND name = N'IDX_NCI_REG_0300_K3_I1_I2')
DROP INDEX [IDX_NCI_REG_0300_K3_I1_I2] ON [CAT].[REG_0300_Object_registry]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CAT].[REG_0300_Object_registry]') AND type in (N'U'))
DROP TABLE [CAT].[REG_0300_Object_registry]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CAT].[REG_0300_Object_registry]') AND type in (N'U'))
BEGIN
CREATE TABLE [CAT].[REG_0300_Object_registry](
	[REG_0300_ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[REG_Object_Name] [nvarchar](256) NOT NULL,
	[REG_Object_Type] [nvarchar](25) NOT NULL,
	[REG_Create_Date] [datetime] NOT NULL,
 CONSTRAINT [PK_REG_0300] PRIMARY KEY CLUSTERED 
(
	[REG_Object_Name] ASC,
	[REG_Object_Type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT [UQ_REG_0300_ID] UNIQUE NONCLUSTERED 
(
	[REG_0300_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING ON

GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[CAT].[REG_0300_Object_registry]') AND name = N'IDX_NCI_REG_0300_K3_I1_I2')
CREATE NONCLUSTERED INDEX [IDX_NCI_REG_0300_K3_I1_I2] ON [CAT].[REG_0300_Object_registry]
(
	[REG_Object_Type] ASC
)
INCLUDE ( 	[REG_0300_ID],
	[REG_Object_Name]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[CAT].[DF_REG_0300_CDate]') AND type = 'D')
BEGIN
ALTER TABLE [CAT].[REG_0300_Object_registry] ADD  CONSTRAINT [DF_REG_0300_CDate]  DEFAULT (getdate()) FOR [REG_Create_Date]
END

GO
