USE [DWMgmt]
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[CAT].[DF_0500_CDate]') AND type = 'D')
BEGIN
ALTER TABLE [CAT].[REG_0500_Parameter_Registry] DROP CONSTRAINT [DF_0500_CDate]
END

GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CAT].[REG_0500_Parameter_Registry]') AND type in (N'U'))
DROP TABLE [CAT].[REG_0500_Parameter_Registry]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CAT].[REG_0500_Parameter_Registry]') AND type in (N'U'))
BEGIN
CREATE TABLE [CAT].[REG_0500_Parameter_Registry](
	[REG_0500_ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[REG_Parameter_Name] [nvarchar](256) NOT NULL,
	[REG_Parameter_Type] [nvarchar](25) NOT NULL,
	[REG_Create_Date] [datetime] NOT NULL,
 CONSTRAINT [PK_REG_0500] PRIMARY KEY CLUSTERED 
(
	[REG_Parameter_Name] ASC,
	[REG_Parameter_Type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT [UQ_REG_0500_ID] UNIQUE NONCLUSTERED 
(
	[REG_0500_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[CAT].[DF_0500_CDate]') AND type = 'D')
BEGIN
ALTER TABLE [CAT].[REG_0500_Parameter_Registry] ADD  CONSTRAINT [DF_0500_CDate]  DEFAULT (getdate()) FOR [REG_Create_Date]
END

GO
