USE [DWMgmt]
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[CAT].[DF_REG_0203_Post_Date]') AND type = 'D')
BEGIN
ALTER TABLE [CAT].[REG_0203_Database_files] DROP CONSTRAINT [DF_REG_0203_Post_Date]
END

GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[CAT].[DF_REG_0203_Growth]') AND type = 'D')
BEGIN
ALTER TABLE [CAT].[REG_0203_Database_files] DROP CONSTRAINT [DF_REG_0203_Growth]
END

GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[CAT].[DF_REG_0203_Size]') AND type = 'D')
BEGIN
ALTER TABLE [CAT].[REG_0203_Database_files] DROP CONSTRAINT [DF_REG_0203_Size]
END

GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CAT].[REG_0203_Database_files]') AND type in (N'U'))
DROP TABLE [CAT].[REG_0203_Database_files]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CAT].[REG_0203_Database_files]') AND type in (N'U'))
BEGIN
CREATE TABLE [CAT].[REG_0203_Database_files](
	[REG_0203_ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[REG_File_ID] [int] NOT NULL,
	[REG_File_Type] [nvarchar](25) NOT NULL,
	[REG_File_Name] [nvarchar](256) NOT NULL,
	[REG_File_Location] [nvarchar](256) NOT NULL,
	[REG_File_Max_Size] [bigint] NOT NULL,
	[REG_File_Growth] [int] NOT NULL,
	[REG_Create_Date] [datetime] NOT NULL,
 CONSTRAINT [PK_REG_0203] PRIMARY KEY CLUSTERED 
(
	[REG_File_ID] ASC,
	[REG_File_Name] ASC,
	[REG_File_Location] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_REG_0203_KeyID] UNIQUE NONCLUSTERED 
(
	[REG_0203_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[CAT].[DF_REG_0203_Size]') AND type = 'D')
BEGIN
ALTER TABLE [CAT].[REG_0203_Database_files] ADD  CONSTRAINT [DF_REG_0203_Size]  DEFAULT ((-1)) FOR [REG_File_Max_Size]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[CAT].[DF_REG_0203_Growth]') AND type = 'D')
BEGIN
ALTER TABLE [CAT].[REG_0203_Database_files] ADD  CONSTRAINT [DF_REG_0203_Growth]  DEFAULT ((10)) FOR [REG_File_Growth]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[CAT].[DF_REG_0203_Post_Date]') AND type = 'D')
BEGIN
ALTER TABLE [CAT].[REG_0203_Database_files] ADD  CONSTRAINT [DF_REG_0203_Post_Date]  DEFAULT (getdate()) FOR [REG_Create_Date]
END

GO
