USE [DWMgmt]
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[CAT].[DF_REG_0103_CDate]') AND type = 'D')
BEGIN
ALTER TABLE [CAT].[REG_0103_Server_Providers] DROP CONSTRAINT [DF_REG_0103_CDate]
END

GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CAT].[REG_0103_Server_Providers]') AND type in (N'U'))
DROP TABLE [CAT].[REG_0103_Server_Providers]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CAT].[REG_0103_Server_Providers]') AND type in (N'U'))
BEGIN
CREATE TABLE [CAT].[REG_0103_Server_Providers](
	[REG_0103_ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[REG_Provider] [nvarchar](256) NOT NULL,
	[REG_Data_Source] [nvarchar](256) NOT NULL,
	[REG_Provider_String] [nvarchar](2000) NOT NULL,
	[REG_Catalog] [nvarchar](256) NOT NULL,
	[REG_Create_Date] [datetime] NOT NULL,
 CONSTRAINT [PK_REG_0103] PRIMARY KEY CLUSTERED 
(
	[REG_Provider] ASC,
	[REG_Data_Source] ASC,
	[REG_Provider_String] ASC,
	[REG_Catalog] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_REG_0103_ID] UNIQUE NONCLUSTERED 
(
	[REG_0103_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[CAT].[DF_REG_0103_CDate]') AND type = 'D')
BEGIN
ALTER TABLE [CAT].[REG_0103_Server_Providers] ADD  CONSTRAINT [DF_REG_0103_CDate]  DEFAULT (getdate()) FOR [REG_Create_Date]
END

GO
