USE [master]
GO
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'DWMgmt')
DROP DATABASE [DWMgmt]
GO
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'DWMgmt')
BEGIN
CREATE DATABASE [DWMgmt] ON  PRIMARY 
( NAME = N'DWMgmt', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL11.IMPERIAL_SENATE\MSSQL\DATA\DWMgmt.mdf' , SIZE = 19960960KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DWMgmt_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\11\MSSQL11.IMPERIAL_SENATE\MSSQL\DATA\DWMgmt_log.ldf' , SIZE = 504KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
END

GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DWMgmt].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DWMgmt] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DWMgmt] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DWMgmt] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DWMgmt] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DWMgmt] SET ARITHABORT OFF 
GO
ALTER DATABASE [DWMgmt] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DWMgmt] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [DWMgmt] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DWMgmt] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DWMgmt] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DWMgmt] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DWMgmt] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DWMgmt] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DWMgmt] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DWMgmt] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DWMgmt] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DWMgmt] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DWMgmt] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DWMgmt] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DWMgmt] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DWMgmt] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DWMgmt] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DWMgmt] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DWMgmt] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DWMgmt] SET  MULTI_USER 
GO
ALTER DATABASE [DWMgmt] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DWMgmt] SET DB_CHAINING OFF 
GO
EXEC sys.sp_db_vardecimal_storage_format N'DWMgmt', N'ON'
GO
ALTER DATABASE [DWMgmt] SET  READ_WRITE 
GO
