USE [DWMgmt]
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[ECO].[DF_R1101_CDate]') AND type = 'D')
BEGIN
ALTER TABLE [ECO].[REG_1101_XML_Namespaces] DROP CONSTRAINT [DF_R1101_CDate]
END

GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ECO].[REG_1101_XML_Namespaces]') AND type in (N'U'))
DROP TABLE [ECO].[REG_1101_XML_Namespaces]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ECO].[REG_1101_XML_Namespaces]') AND type in (N'U'))
BEGIN
CREATE TABLE [ECO].[REG_1101_XML_Namespaces](
	[REG_1101_ID] [int] IDENTITY(1,1) NOT NULL,
	[REG_Namespace] [nvarchar](256) NOT NULL,
	[REG_NS_Link] [nvarchar](256) NOT NULL,
	[REG_Create_Date] [datetime] NOT NULL,
 CONSTRAINT [PK_REG_1101] PRIMARY KEY CLUSTERED 
(
	[REG_Namespace] ASC,
	[REG_NS_Link] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_R1101_ID] UNIQUE NONCLUSTERED 
(
	[REG_1101_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[ECO].[DF_R1101_CDate]') AND type = 'D')
BEGIN
ALTER TABLE [ECO].[REG_1101_XML_Namespaces] ADD  CONSTRAINT [DF_R1101_CDate]  DEFAULT (getdate()) FOR [REG_Create_Date]
END

GO
