USE [DWMgmt]
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[ECO].[DF_R1104_CDate]') AND type = 'D')
BEGIN
ALTER TABLE [ECO].[REG_1104_XML_Property_Values] DROP CONSTRAINT [DF_R1104_CDate]
END

GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ECO].[REG_1104_XML_Property_Values]') AND type in (N'U'))
DROP TABLE [ECO].[REG_1104_XML_Property_Values]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ECO].[REG_1104_XML_Property_Values]') AND type in (N'U'))
BEGIN
CREATE TABLE [ECO].[REG_1104_XML_Property_Values](
	[REG_1104_ID] [int] IDENTITY(1,1) NOT NULL,
	[REG_Value] [nvarchar](4000) NOT NULL,
	[REG_Create_Date] [datetime] NOT NULL,
 CONSTRAINT [pk_REG_1104] PRIMARY KEY CLUSTERED 
(
	[REG_Value] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_R1104_ID] UNIQUE NONCLUSTERED 
(
	[REG_1104_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[ECO].[DF_R1104_CDate]') AND type = 'D')
BEGIN
ALTER TABLE [ECO].[REG_1104_XML_Property_Values] ADD  CONSTRAINT [DF_R1104_CDate]  DEFAULT (getdate()) FOR [REG_Create_Date]
END

GO
