USE [DWMgmt]
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[ECO].[DF_R1100_CDate]') AND type = 'D')
BEGIN
ALTER TABLE [ECO].[REG_1100_XML_Schema_Registry] DROP CONSTRAINT [DF_R1100_CDate]
END

GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ECO].[REG_1100_XML_Schema_Registry]') AND type in (N'U'))
DROP TABLE [ECO].[REG_1100_XML_Schema_Registry]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ECO].[REG_1100_XML_Schema_Registry]') AND type in (N'U'))
BEGIN
CREATE TABLE [ECO].[REG_1100_XML_Schema_Registry](
	[REG_1100_ID] [int] IDENTITY(1,1) NOT NULL,
	[REG_XML_Class] [nvarchar](256) NOT NULL,
	[REG_Schema_Name] [nvarchar](256) NOT NULL,
	[REG_Schema_Path] [nvarchar](2000) NOT NULL,
	[REG_Create_Date] [datetime] NOT NULL,
 CONSTRAINT [PK_REG_1100] PRIMARY KEY NONCLUSTERED 
(
	[REG_XML_Class] ASC,
	[REG_Schema_Name] ASC,
	[REG_Schema_Path] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_R1100_ID] UNIQUE CLUSTERED 
(
	[REG_1100_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[ECO].[DF_R1100_CDate]') AND type = 'D')
BEGIN
ALTER TABLE [ECO].[REG_1100_XML_Schema_Registry] ADD  CONSTRAINT [DF_R1100_CDate]  DEFAULT (getdate()) FOR [REG_Create_Date]
END

GO
