USE [DWMgmt]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[ECO].[FK_SN_LNK_1101]') AND parent_object_id = OBJECT_ID(N'[ECO].[LNK_1100_1101_Schema_Namespaces]'))
ALTER TABLE [ECO].[LNK_1100_1101_Schema_Namespaces] DROP CONSTRAINT [FK_SN_LNK_1101]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[ECO].[FK_SN_LNK_1100]') AND parent_object_id = OBJECT_ID(N'[ECO].[LNK_1100_1101_Schema_Namespaces]'))
ALTER TABLE [ECO].[LNK_1100_1101_Schema_Namespaces] DROP CONSTRAINT [FK_SN_LNK_1100]
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[ECO].[DF_L1100_1101_Term]') AND type = 'D')
BEGIN
ALTER TABLE [ECO].[LNK_1100_1101_Schema_Namespaces] DROP CONSTRAINT [DF_L1100_1101_Term]
END

GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[ECO].[DF_L1100_1101_Post]') AND type = 'D')
BEGIN
ALTER TABLE [ECO].[LNK_1100_1101_Schema_Namespaces] DROP CONSTRAINT [DF_L1100_1101_Post]
END

GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ECO].[LNK_1100_1101_Schema_Namespaces]') AND type in (N'U'))
DROP TABLE [ECO].[LNK_1100_1101_Schema_Namespaces]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ECO].[LNK_1100_1101_Schema_Namespaces]') AND type in (N'U'))
BEGIN
CREATE TABLE [ECO].[LNK_1100_1101_Schema_Namespaces](
	[LNK_1100_1101_ID] [int] IDENTITY(1,1) NOT NULL,
	[LNK_FK_1100_ID] [int] NOT NULL,
	[LNK_FK_1101_ID] [int] NOT NULL,
	[LNK_Post_Date] [datetime] NULL,
	[LNK_Term_Date] [datetime] NOT NULL,
 CONSTRAINT [PK_LNK_1100_1101] PRIMARY KEY CLUSTERED 
(
	[LNK_FK_1100_ID] ASC,
	[LNK_FK_1101_ID] ASC,
	[LNK_Term_Date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_L1100_1101_ID] UNIQUE NONCLUSTERED 
(
	[LNK_1100_1101_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[ECO].[DF_L1100_1101_Post]') AND type = 'D')
BEGIN
ALTER TABLE [ECO].[LNK_1100_1101_Schema_Namespaces] ADD  CONSTRAINT [DF_L1100_1101_Post]  DEFAULT (getdate()) FOR [LNK_Post_Date]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[ECO].[DF_L1100_1101_Term]') AND type = 'D')
BEGIN
ALTER TABLE [ECO].[LNK_1100_1101_Schema_Namespaces] ADD  CONSTRAINT [DF_L1100_1101_Term]  DEFAULT ('12/31/2099') FOR [LNK_Term_Date]
END

GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[ECO].[FK_SN_LNK_1100]') AND parent_object_id = OBJECT_ID(N'[ECO].[LNK_1100_1101_Schema_Namespaces]'))
ALTER TABLE [ECO].[LNK_1100_1101_Schema_Namespaces]  WITH CHECK ADD  CONSTRAINT [FK_SN_LNK_1100] FOREIGN KEY([LNK_FK_1100_ID])
REFERENCES [ECO].[REG_1100_XML_Schema_Registry] ([REG_1100_ID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[ECO].[FK_SN_LNK_1100]') AND parent_object_id = OBJECT_ID(N'[ECO].[LNK_1100_1101_Schema_Namespaces]'))
ALTER TABLE [ECO].[LNK_1100_1101_Schema_Namespaces] CHECK CONSTRAINT [FK_SN_LNK_1100]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[ECO].[FK_SN_LNK_1101]') AND parent_object_id = OBJECT_ID(N'[ECO].[LNK_1100_1101_Schema_Namespaces]'))
ALTER TABLE [ECO].[LNK_1100_1101_Schema_Namespaces]  WITH CHECK ADD  CONSTRAINT [FK_SN_LNK_1101] FOREIGN KEY([LNK_FK_1101_ID])
REFERENCES [ECO].[REG_1101_XML_Namespaces] ([REG_1101_ID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[ECO].[FK_SN_LNK_1101]') AND parent_object_id = OBJECT_ID(N'[ECO].[LNK_1100_1101_Schema_Namespaces]'))
ALTER TABLE [ECO].[LNK_1100_1101_Schema_Namespaces] CHECK CONSTRAINT [FK_SN_LNK_1101]
GO
