CREATE TABLE [ECO].[LNK_1100_LIB_Docuent_Paths] (
    [LNK_1100_DOC_ID]    INT      IDENTITY (1, 1) NOT NULL,
    [LNK_FK_1100_ID]     INT      NOT NULL,
    [LNK_FK_Document_ID] INT      NOT NULL,
    [LNK_Post_Date]      DATETIME CONSTRAINT [DF_L1100_DOC_Post] DEFAULT (getdate()) NULL,
    [LNK_Term_Date]      DATETIME CONSTRAINT [DF_L1100_DOC_Term] DEFAULT ('12/31/2099') NOT NULL,
    CONSTRAINT [PK_LNK_1100_DOC_ID] PRIMARY KEY CLUSTERED ([LNK_FK_1100_ID] ASC, [LNK_FK_Document_ID] ASC, [LNK_Term_Date] ASC),
    CONSTRAINT [FK_EDP_LNK_1100] FOREIGN KEY ([LNK_FK_1100_ID]) REFERENCES [ECO].[REG_1100_XML_Schema_Registry] ([REG_1100_ID]),
    CONSTRAINT [FK_EDP_LNK_DOC_ID] FOREIGN KEY ([LNK_FK_Document_ID]) REFERENCES [LIB].[REG_Documents] ([Document_ID]),
    CONSTRAINT [UQ_L1100_DOC_ID] UNIQUE NONCLUSTERED ([LNK_1100_DOC_ID] ASC)
);

