CREATE TABLE [ECO].[REG_1103_XML_Node_Properties] (
    [REG_1103_ID]       INT            IDENTITY (1, 1) NOT NULL,
    [REG_Property_Name] NVARCHAR (256) NOT NULL,
    [REG_Create_Date]   DATETIME       CONSTRAINT [DF_R1103_CDate] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [pk_REG_1103] PRIMARY KEY CLUSTERED ([REG_Property_Name] ASC),
    CONSTRAINT [UQ_R1103_ID] UNIQUE NONCLUSTERED ([REG_1103_ID] ASC)
);

