CREATE TABLE [ECO].[REG_1104_XML_Property_Values] (
    [REG_1104_ID]     INT             IDENTITY (1, 1) NOT NULL,
    [REG_Value]       NVARCHAR (4000) NOT NULL,
    [REG_Create_Date] DATETIME        CONSTRAINT [DF_R1104_CDate] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [pk_REG_1104] PRIMARY KEY CLUSTERED ([REG_Value] ASC),
    CONSTRAINT [UQ_R1104_ID] UNIQUE NONCLUSTERED ([REG_1104_ID] ASC)
);

