CREATE TABLE [ECO].[REG_1100_XML_Schema_Registry] (
    [REG_1100_ID]     INT            IDENTITY (1, 1) NOT NULL,
    [REG_XML_Class]   NVARCHAR (256) NOT NULL,
    [REG_Schema_Name] NVARCHAR (256) NOT NULL,
    [REG_Create_Date] DATETIME       CONSTRAINT [DF_R1100_CDate] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_REG_1100] PRIMARY KEY NONCLUSTERED ([REG_XML_Class] ASC, [REG_Schema_Name] ASC),
    CONSTRAINT [UQ_R1100_ID] UNIQUE CLUSTERED ([REG_1100_ID] ASC)
);

