CREATE TABLE [CAT].[LNK_Tier1_Peers] (
    [T1P_ID]         INT      IDENTITY (1, 1) NOT NULL,
    [LNK_FK_0100_ID] INT      NOT NULL,
    [LNK_FK_0101_ID] INT      NOT NULL,
    [LNK_FK_0102_ID] INT      NOT NULL,
    [LNK_FK_0103_ID] INT      CONSTRAINT [DF_T1P_K5] DEFAULT ((0)) NOT NULL,
    [LNK_Post_Date]  DATETIME CONSTRAINT [DF_T1P_Post_Date] DEFAULT (getdate()) NOT NULL,
    [LNK_Term_Date]  DATETIME CONSTRAINT [DF_T1P_Term_Date] DEFAULT ('12/31/2099') NOT NULL,
    CONSTRAINT [PK_T1P] PRIMARY KEY CLUSTERED ([LNK_FK_0100_ID] ASC, [LNK_FK_0101_ID] ASC, [LNK_FK_0102_ID] ASC, [LNK_FK_0103_ID] ASC, [LNK_Term_Date] ASC),
    CONSTRAINT [CHK_FK_0100_ID_GT_0] CHECK ([LNK_FK_0100_ID]>(0)),
    CONSTRAINT [FK_LNK_Tier1_Peers_REG_0100_Server_Registry] FOREIGN KEY ([LNK_FK_0100_ID]) REFERENCES [CAT].[REG_0100_Server_Registry] ([REG_0100_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_LNK_Tier1_Peers_REG_0101_Linked_Server_Settings] FOREIGN KEY ([LNK_FK_0101_ID]) REFERENCES [CAT].[REG_0101_Linked_Server_Settings] ([REG_0101_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_LNK_Tier1_Peers_REG_0102_Publication_Replication_Server_Settings] FOREIGN KEY ([LNK_FK_0102_ID]) REFERENCES [CAT].[REG_0102_Publication_Replication_Server_Settings] ([REG_0102_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_LNK_Tier1_Peers_REG_0103_Server_Providers] FOREIGN KEY ([LNK_FK_0103_ID]) REFERENCES [CAT].[REG_0103_Server_Providers] ([REG_0103_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [UQ_T1P_ID] UNIQUE NONCLUSTERED ([T1P_ID] ASC) WITH (FILLFACTOR = 90)
);


GO


CREATE TRIGGER [CAT].[TGR_T1_Current_Properties]
    ON  [CAT].[LNK_Tier1_Peers]
    INSTEAD OF INSERT
 AS  
 BEGIN
  SET NOCOUNT ON;
     
         
     UPDATE lnk SET LNK_Term_Date = getdate()
     FROM CAT.LNK_Tier1_Peers AS lnk
     LEFT JOIN inserted AS i
     ON lnk.LNK_FK_0100_ID = i.LNK_FK_0100_ID
     AND lnk.LNK_FK_0101_ID = i.LNK_FK_0101_ID
     AND lnk.LNK_FK_0102_ID = i.LNK_FK_0102_ID
     AND lnk.LNK_FK_0103_ID = i.LNK_FK_0103_ID
     WHERE (lnk.LNK_Term_Date >= getdate()
	 OR lnk.LNK_Term_Date < cast(0 as datetime))
	 AND lnk.T1P_ID IS NULL
	 
     
     INSERT INTO CAT.LNK_Tier1_Peers (LNK_FK_0100_ID, LNK_FK_0101_ID, LNK_FK_0102_ID, LNK_FK_0103_ID)

     SELECT i.LNK_FK_0100_ID, i.LNK_FK_0101_ID, i.LNK_FK_0102_ID, i.LNK_FK_0103_ID
     FROM inserted AS i
     LEFT JOIN CAT.LNK_Tier1_Peers AS p
     ON p.LNK_FK_0100_ID = i.LNK_FK_0100_ID
     AND p.LNK_FK_0101_ID = i.LNK_FK_0101_ID
     AND p.LNK_FK_0102_ID = i.LNK_FK_0102_ID
     AND p.LNK_FK_0103_ID = i.LNK_FK_0103_ID
     AND p.LNK_Term_Date >= GETDATE()
     WHERE p.T1P_ID IS NULL
     
 END