CREATE TABLE [CAT].[LNK_0300_0400_Object_Column_Collection] (
    [LNK_T4_ID]      INT      IDENTITY (1, 1) NOT NULL,
    [LNK_FK_T3_ID]   INT      NOT NULL,
    [LNK_FK_0300_ID] INT      NOT NULL,
    [LNK_FK_0400_ID] INT      NOT NULL,
    [LNK_Rank]       INT      CONSTRAINT [DF_T4L_Rank] DEFAULT ((0)) NOT NULL,
    [LNK_Post_Date]  DATETIME CONSTRAINT [DF_T4L_Post_Date] DEFAULT (getdate()) NOT NULL,
    [LNK_Term_Date]  DATETIME CONSTRAINT [DF_T4L_Term_Date] DEFAULT ('12/31/2099') NOT NULL,
    CONSTRAINT [PK_LNK_0300_0400] PRIMARY KEY CLUSTERED ([LNK_FK_T3_ID] ASC, [LNK_FK_0300_ID] ASC, [LNK_FK_0400_ID] ASC, [LNK_Rank] ASC, [LNK_Term_Date] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_LNK_0300_0400_LNK_T3_ID] FOREIGN KEY ([LNK_FK_T3_ID]) REFERENCES [CAT].[LNK_0204_0300_Schema_Binding] ([LNK_T3_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_LNK_0300_0400_REG_0300_Object_Registry] FOREIGN KEY ([LNK_FK_0300_ID]) REFERENCES [CAT].[REG_0300_Object_Registry] ([REG_0300_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_LNK_0300_0400_REG_0400_Column_Collection] FOREIGN KEY ([LNK_FK_0400_ID]) REFERENCES [CAT].[REG_0400_Column_Registry] ([REG_0400_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [UQ_LNK_0300_0400_ID] UNIQUE NONCLUSTERED ([LNK_T4_ID] ASC) WITH (FILLFACTOR = 90)
);


GO


CREATE TRIGGER [CAT].[TGR_L3_Object_Column_Collection]
   ON  [CAT].[LNK_0300_0400_Object_Column_Collection]
   INSTEAD OF INSERT
AS 
BEGIN
	SET NOCOUNT ON;

    UPDATE lat SET LNK_Term_Date = getdate()
    FROM CAT.LNK_0300_0400_Object_Column_Collection AS lat
    LEFT JOIN inserted AS i
    ON lat.LNK_FK_T3_ID = i.LNK_FK_T3_ID
    AND lat.LNK_FK_0300_ID = i.LNK_FK_0300_ID
    AND lat.LNK_FK_0400_ID = i.LNK_FK_0400_ID
	AND lat.LNK_Rank = i.LNK_Rank
    WHERE lat.LNK_Term_Date >= getdate()
    AND i.LNK_FK_T3_ID IS NULL

    ; WITH Latch3 (LNK_FK_T3_ID, LNK_FK_0300_ID, LNK_FK_0400_ID, LNK_Rank)
    AS (
        SELECT LNK_FK_T3_ID, LNK_FK_0300_ID, LNK_FK_0400_ID, LNK_Rank
        FROM CAT.LNK_0300_0400_Object_Column_Collection
        WHERE LNK_Term_Date > getdate()
        GROUP BY LNK_FK_T3_ID, LNK_FK_0300_ID, LNK_FK_0400_ID, LNK_Rank
        )
	
    INSERT INTO CAT.LNK_0300_0400_Object_Column_Collection (LNK_FK_T3_ID, LNK_FK_0300_ID, LNK_FK_0400_ID, LNK_Rank)
    SELECT DISTINCT LNK_FK_T3_ID, LNK_FK_0300_ID, LNK_FK_0400_ID, LNK_Rank
    FROM inserted 
    EXCEPT
    SELECT LNK_FK_T3_ID, LNK_FK_0300_ID, LNK_FK_0400_ID, LNK_Rank
    FROM Latch3

END