CREATE TABLE [CAT].[LNK_Tier2_Peers] (
    [T2P_ID]         INT      IDENTITY (1, 1) NOT NULL,
    [LNK_FK_T2_ID]   INT      NOT NULL,
    [LNK_FK_0200_ID] INT      NOT NULL,
    [LNK_FK_0201_ID] INT      NOT NULL,
    [LNK_FK_0202_ID] INT      NOT NULL,
    [LNK_FK_0203_ID] INT      NOT NULL,
    [LNK_FK_0204_ID] INT      NOT NULL,
    [LNK_FK_0205_ID] INT      CONSTRAINT [DF_T2P_FK_0205] DEFAULT ((0)) NOT NULL,
    [LNK_Post_Date]  DATETIME CONSTRAINT [DF_T2P_Post_Date] DEFAULT (getdate()) NOT NULL,
    [LNK_Term_Date]  DATETIME CONSTRAINT [DF_T2P_Term_Date] DEFAULT ('12/31/2099') NOT NULL,
    CONSTRAINT [PK_T2P] PRIMARY KEY CLUSTERED ([LNK_FK_T2_ID] ASC, [LNK_FK_0200_ID] ASC, [LNK_FK_0201_ID] ASC, [LNK_FK_0202_ID] ASC, [LNK_FK_0203_ID] ASC, [LNK_FK_0204_ID] ASC, [LNK_FK_0205_ID] ASC, [LNK_Term_Date] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CHK_FK_0200_ID_GT_0] CHECK ([LNK_FK_0200_ID]>(0)),
    CONSTRAINT [CHK_FK_T2_ID_GT_0] CHECK ([LNK_FK_T2_ID]>(0)),
    CONSTRAINT [FK_LNK_Tier2_Peers_REG_0200_Database_Registry] FOREIGN KEY ([LNK_FK_0200_ID]) REFERENCES [CAT].[REG_0200_Database_Registry] ([REG_0200_ID]),
    CONSTRAINT [FK_LNK_Tier2_Peers_REG_0201_Database_Extended_Properties_A] FOREIGN KEY ([LNK_FK_0201_ID]) REFERENCES [CAT].[REG_0201_Database_Extended_Properties_A] ([REG_0201_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_LNK_Tier2_Peers_REG_0202_Database_Extended_Properties_B] FOREIGN KEY ([LNK_FK_0202_ID]) REFERENCES [CAT].[REG_0202_Database_Extended_Properties_B] ([REG_0202_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_LNK_Tier2_Peers_REG_0203_Database_Files] FOREIGN KEY ([LNK_FK_0203_ID]) REFERENCES [CAT].[REG_0203_Database_Files] ([REG_0203_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_LNK_Tier2_Peers_REG_0204_Database_Schemas] FOREIGN KEY ([LNK_FK_0204_ID]) REFERENCES [CAT].[REG_0204_Database_Schemas] ([REG_0204_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_LNK_Tier2_Peers_REG_0205_Database_Maintenance_Properties] FOREIGN KEY ([LNK_FK_0205_ID]) REFERENCES [CAT].[REG_0205_Database_Maintenance_Properties_Old] ([REG_0205_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [UQ_T2P_ID] UNIQUE NONCLUSTERED ([T2P_ID] ASC) WITH (FILLFACTOR = 90)
);


GO


CREATE TRIGGER [CAT].[TGR_T2_Current_Properties]
    ON  [CAT].[LNK_Tier2_Peers]
    INSTEAD OF INSERT
 AS  
 BEGIN
  SET NOCOUNT ON;
     
         
    UPDATE lnk SET LNK_Term_Date = getdate()
    FROM CAT.LNK_Tier2_Peers AS lnk
    LEFT JOIN inserted AS i
    ON lnk.LNK_FK_T2_ID = i.LNK_FK_T2_ID
    AND lnk.LNK_FK_0200_ID = i.LNK_FK_0200_ID
    AND lnk.LNK_FK_0201_ID = i.LNK_FK_0201_ID
    AND lnk.LNK_FK_0202_ID = i.LNK_FK_0202_ID
    AND lnk.LNK_FK_0203_ID = i.LNK_FK_0203_ID
    AND lnk.LNK_FK_0204_ID = i.LNK_FK_0204_ID
    AND lnk.LNK_FK_0205_ID = i.LNK_FK_0205_ID
    WHERE (lnk.LNK_Term_Date >= getdate()
	OR lnk.LNK_Term_Date < cast(0 as datetime))
    AND i.LNK_FK_T2_ID IS NULL
     

    INSERT INTO CAT.LNK_Tier2_Peers (LNK_FK_T2_ID, LNK_FK_0200_ID, LNK_FK_0201_ID, LNK_FK_0202_ID
    , LNK_FK_0203_ID, LNK_FK_0204_ID, LNK_FK_0205_ID)
    
    SELECT i.LNK_FK_T2_ID, i.LNK_FK_0200_ID, i.LNK_FK_0201_ID, i.LNK_FK_0202_ID
    , i.LNK_FK_0203_ID, i.LNK_FK_0204_ID, i.LNK_FK_0205_ID
    FROM inserted AS i
    LEFT JOIN CAT.LNK_Tier2_Peers AS p
    ON p.LNK_FK_T2_ID = i.LNK_FK_T2_ID
    AND p.LNK_FK_0200_ID = i.LNK_FK_0200_ID
    AND p.LNK_FK_0201_ID = i.LNK_FK_0201_ID
    AND p.LNK_FK_0202_ID = i.LNK_FK_0202_ID
    AND p.LNK_FK_0203_ID = i.LNK_FK_0203_ID
    AND p.LNK_FK_0204_ID = i.LNK_FK_0204_ID
    AND p.LNK_FK_0205_ID = i.LNK_FK_0205_ID
	AND p.LNK_Term_Date >= GETDATE()
	WHERE p.T2P_ID IS NULL
     
 END