CREATE TABLE [CAT].[LNK_0200_0205_Database_Maintenance_Links] (
    [LNK_TBL_ID]        INT      IDENTITY (1, 1) NOT NULL,
    [LNK_FK_T2_ID]      INT      NOT NULL,
    [LNK_FK_T3_ID]      INT      CONSTRAINT [DF_FK_T3_ID] DEFAULT ((0)) NOT NULL,
    [LNK_FK_T4_ID]      INT      CONSTRAINT [DF_FK_T4_ID] DEFAULT ((0)) NOT NULL,
    [LNK_FK_0205_ID]    INT      NOT NULL,
    [LNK_Min_Exec_Time] TIME (7) CONSTRAINT [DF_LDM_Min_Exec] DEFAULT ('00:00:00.000') NOT NULL,
    [LNK_Max_Exec_Time] TIME (7) CONSTRAINT [DF_LDM_Max_Exec] DEFAULT ('23:59:59.999') NOT NULL,
    [LNK_Post_Date]     DATETIME CONSTRAINT [DF_LDM_Post] DEFAULT (getdate()) NOT NULL,
    [LNK_Term_Date]     DATETIME CONSTRAINT [DF_LDM_Term] DEFAULT ('12/31/2099') NOT NULL,
    [LNK_Day_Modulus]   TINYINT  CONSTRAINT [LNK_0205_Day_Mod] DEFAULT ((7)) NULL,
    CONSTRAINT [pk_LNK_0200_0205] PRIMARY KEY CLUSTERED ([LNK_FK_0205_ID] ASC, [LNK_FK_T2_ID] ASC, [LNK_FK_T3_ID] ASC, [LNK_FK_T4_ID] ASC, [LNK_Term_Date] ASC)
);

