CREATE TABLE [CAT].[REG_0204_Database_Schemas] (
    [REG_0204_ID]     INT            IDENTITY (1, 1) NOT NULL,
    [REG_Schema_Name] NVARCHAR (256) NOT NULL,
    [REG_Create_Date] DATETIME       CONSTRAINT [DF_REG_0204_CDate] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_REG_0204] PRIMARY KEY CLUSTERED ([REG_Schema_Name] ASC),
    CONSTRAINT [UQ_REG_0204_ID] UNIQUE NONCLUSTERED ([REG_0204_ID] ASC)
);

